name: my_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '^3.9.0'
dependencies:
  flutter:
    sdk: flutter
  
  # Firebase Services
  firebase_core: ^2.31.0
  cloud_firestore: ^4.17.3
  firebase_auth: ^4.19.5

  # State Management
  provider: ^6.1.1 # Version might change, but this is the package

  # Essential Native Plugins for Your App:
  url_launcher: ^6.2.2          # For the "Contact Developer" email button
  wakelock_plus: ^1.2.0         # Prevents screen from locking (Wake Lock)
  sensors_plus: ^5.0.0          # Accesses the Proximity Sensor
  volume_controller: ^3.4.1     # Listens for Volume Button presses
  flutter_foreground_task: ^6.1.1 # Keeps the timer running in the background (Foreground Service)

  # UI
  numberpicker: ^2.1.2

  # Audio
  just_audio: ^0.9.36

  cupertino_icons: ^1.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/ # This line includes the new assets directory
